### ISSUE TITLE
Question: Does AIP have API to support to revoke the document for IT Admins

### ISSUE THREAD

**Issue by ericsyh** [Azure-Samples/AIP-Custom-Tracking-Portal-Samples#1]
We want to build a custom portal for IT Admins to review and manage all the documents under AIP. 

The blog [how-to-build-a-custom-aip-tracking-portal](https://techcommunity.microsoft.com/t5/azure-information-protection/how-to-build-a-custom-aip-tracking-portal/ba-p/875849#comment-on-this) helps a lot on how to collect the client activities and shared documents info but seems do not support for some admin actions like revoke the document permission. 

So we wanna check whether any solution can we get for this scenario？

**Comment by ericsyh** [comment]
@RafaelDominguez PTAL

**Comment by Morotai** [comment]
Hi @ericsyh, please reach out to the AIP team via their Yammer community at Yammer/askipteam I believe. I left that team last year but I believe there was an API from the original portal but I never used it and don't know if it's still available.

**Comment by ericsyh** [comment]
@RafaelDominguez ok, thx. I will check with them in Yammer.
